export const theme = {
  colors: {
    white: '#fff',
    black: '#000000',
    text: '#2a2a2a',
    background: '#E7ECF2',
    primary: '#3f51b5',
    secondary: '#303f9f',
    third: '#dcdcdc',
    accent: 'orange',
    border: '#E4E9F0',
    green: 'green',
    red: 'red',
  },
  space: {
    xs: '0px',
    s: '2px',
    m: '4px',
    ml: '8px',
    l: '16px',
    xl: '32px',
    xxl: '64px',
    xxx: '128px',
    xxxl: '256px',
  },
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'system-ui, sans-serif',
    monospace: 'Menlo, monospace',
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  fontSizes: {
    xs: '12px',
    s: '14px',
    m: '16px',
    ml: '24px',
    l: '32px',
    xl: '64px',
  },
  radii: {
    none: '0',
    normal: '5px',
    round: '50%',
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
};
